doctrine:
    dbal:
        connections:
            default:
                driver: 'pdo_mysql'
                charset: UTF8
                url: "%env(resolve:DATABASE_URL)%"
                profiling:  true
        types:
            endpoint: Notifications\Infrastructure\Persistence\Doctrine\Types\EndpointType
            keys: Notifications\Infrastructure\Persistence\Doctrine\Types\KeysType
            expirationTime: Notifications\Infrastructure\Persistence\Doctrine\Types\ExpirationTimeType
            
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        controller_resolver:
            auto_mapping: true
        mappings:
            Notifications:
                is_bundle: false
                type: xml
                dir: "%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping"
                prefix: 'Notifications\Domain\Entity'
