#!/bin/bash

# Create the var directory if it does not exist
function create_var_directory() {
    DIR_VAR=var
    if [ ! -d "$DIR_VAR" ]; then
        mkdir $DIR_VAR
    fi
}

function build_php_image() {
    docker build -t notifications-php:latest docker/php
}


create_var_directory
build_php_image
bin/composer install
