services:
  nginx-devlocal:
    container_name: "notifications-nginx"
    build:
      context: ../.
      dockerfile: docker/nginx/Dockerfile
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - php-devlocal
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - "$PWD/..:/var/notifications"
    ports:
      - "33080:80"
      - "2443:443"
    networks:
      - notifications-networks

  php-devlocal:
    container_name: "notifications-php"
    build:
      context: ../.
      dockerfile: docker/php/Dockerfile
      tags:
        - php-notifications
    user: 1000:1000
    volumes:
      - "$PWD/..:/var/notifications"
      - "$PWD/..:$PWD/.."
    working_dir: $PWD/..
    networks:
      - notifications-networks

networks:
  notifications-networks:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdff:1:1::/112
          gateway: fdff:1:1::1

volumes:
  notifications-db:
