services:
  nginx-devlocal:
    container_name: "notifications-nginx"
    build:
      context: ../.
      dockerfile: docker/nginx/Dockerfile
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - php-devlocal
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - "$PWD/..:/var/notifications"
    ports:
      - "11480:80"
      - "2443:443"
    networks:
      - notifications-network

  php-devlocal:
    container_name: "notifications-php"
    build:
      context: ../.
      dockerfile: docker/php/Dockerfile
      tags:
        - php-notifications
    user: 1000:1000
    volumes:
      - "$PWD/..:/var/notifications"
      - "$PWD/..:$PWD/.."
    working_dir: $PWD/..
    networks:
      - notifications-network

  notifications-mariadb:
    image: notifications-mariadb:latest
    container_name: "notifications-mariadb"
    build:
      context: .
      dockerfile: mariadb/Dockerfile
      tags:
        - latest
    restart: always
    volumes:
      - /home/debian/projet/notifications-mariadb/_data:/var/lib/mysql
      - ../../mariabackup:/backup
    env_file:
      - ./mariadb/db.env
    networks:
      - notifications-network

  notifications-phpmyadmin:
    image: phpmyadmin
    container_name: "notifications-phpmyadmin"
    restart: always
    environment:
      PMA_HOST: notifications-mariadb
    depends_on:
      - notifications-mariadb
    ports:
      - "172.17.0.1:11402:80"
    networks:
      - notifications-network

networks:
  notifications-network:
    driver: bridge
    name: notifications-network
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdff:1:24::/112
          gateway: fdff:1:24::1

volumes:
  notifications-db:
